# Generated by Django 5.0.3 on 2024-03-31 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время')),
                ('action', models.CharField(blank=True, max_length=200, null=True, verbose_name='Действие')),
                ('nice_habit_bool', models.BooleanField(default=False, verbose_name='Признак полезной привычки')),
                ('period', models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в 3 дня', 'Раз в 3 дня'), ('Раз в неделю', 'Раз в неделю')], default='Раз в день', verbose_name='период')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение')),
                ('time_on_action', models.TimeField(blank=True, null=True, verbose_name='Время на выполнение')),
                ('is_published', models.BooleanField(default=False, verbose_name='Признак публикации')),
                ('nice_habit', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.habit', verbose_name='Связанная привычка')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец привычки')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
