# Generated by Django 5.0.3 on 2024-04-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_alter_habit_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='period',
        ),
    ]
