# Generated by Django 5.0.3 on 2024-04-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0005_remove_habit_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='period',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='периодичность'),
        ),
    ]
